# Generated by Django 5.0.6 on 2024-05-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='makers/image/default.png', upload_to='makers/image/', verbose_name='Avatar'),
        ),
    ]
