# Generated by Django 5.0.6 on 2024-05-14 13:02

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='video',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='video',
            name='users',
            field=models.ManyToManyField(to='app.person', verbose_name='Users'),
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('file', models.FileField(upload_to='tabs/', verbose_name='File')),
                ('users', models.ManyToManyField(to='app.person', verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Tab',
                'verbose_name_plural': 'Tabs',
            },
        ),
    ]
