# Generated by Django 5.0.6 on 2024-05-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_video_options_alter_person_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tab',
            old_name='title',
            new_name='musician',
        ),
        migrations.AddField(
            model_name='tab',
            name='song_name',
            field=models.CharField(default=None, max_length=100, verbose_name='Song'),
            preserve_default=False,
        ),
    ]
