# Generated by Django 5.0.6 on 2024-05-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_title_tab_musician_tab_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
    ]
