# Generated by Django 5.0.6 on 2024-05-14 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tab_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='–', max_length=100, verbose_name='First name')),
                ('username', models.CharField(default='–', max_length=100, verbose_name='Username')),
                ('last_name', models.CharField(default='–', max_length=100, verbose_name='Last name')),
                ('image', models.FileField(default='musicians/avatars/default.png', upload_to='musicians/avatars/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Musician',
                'verbose_name_plural': 'Musicians',
            },
        ),
        migrations.AlterField(
            model_name='tab',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.musician', verbose_name='Musician'),
        ),
    ]
