# Generated by Django 5.0.6 on 2024-05-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_musician_alter_tab_musician'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='album',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Album'),
        ),
        migrations.AddField(
            model_name='tab',
            name='year',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='song_name',
            field=models.CharField(default='–', max_length=100, verbose_name='Song'),
        ),
    ]
