# Generated by Django 5.0.6 on 2024-05-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tab_album_tab_year_alter_musician_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='tab',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Slug'),
        ),
    ]
