# Generated by Django 5.0.6 on 2024-05-15 14:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_anecdote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anecdote',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Anecdote'),
        ),
    ]
