# Generated by Django 5.0.6 on 2024-05-18 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='song',
            field=models.FileField(default='makers/songs/Derek_Pope_-_Encore.mp3', upload_to='makers/songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])], verbose_name='Song'),
        ),
    ]
