# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'templates/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import configparser
import os


def get_config(name: str) -> str:
    config = configparser.ConfigParser()
    config.read("settings/config.ini")
    return config['APP'][name]


class Ui_Main(object):

    def __init__(self):
        self.SettingsGrid = None
        self.pushButton = None
        self.title = None
        self.TitleLayout = None
        self.gridLayoutWidget_3 = None
        self.gridLayoutWidget_2 = None
        self.gridLayoutWidget = None
        self.centralWidget = None
        self.mainGrid = None
        self.finderButton = None
        self.statusbar = None
        self.menubar = None

    def setupGrid(self, widget: QtWidgets.QWidget | QtWidgets.QGridLayout, object_name: str, size: list[int]) -> QtWidgets.QWidget:
        layoutWidget = QtWidgets.QWidget(widget)
        layoutWidget.setGeometry(QtCore.QRect(*size))
        layoutWidget.setObjectName(object_name)
        return layoutWidget

    def setupFont(self, family: str, size: int, is_bold: bool, weight: int, style_strategy: QtGui.QFont = None):
        font = QtGui.QFont()
        font.setFamily(family)
        font.setPointSize(size)
        font.setBold(is_bold)
        font.setWeight(weight)
        if style_strategy:
            font.setStyleStrategy(style_strategy)
        return font

    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(800, 614)

        app_icon = QtGui.QIcon()
        settings_icon_path = get_config(name="SETTINGS_ICON")
        app_icon.addPixmap(QtGui.QPixmap(os.getcwd() + settings_icon_path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main.setWindowIcon(app_icon)

        font = self.setupFont("PT Serif", 16, True, 50)

        # Setup Central Widget
        self.centralWidget = QtWidgets.QWidget(Main)
        self.centralWidget.setFont(font)
        self.centralWidget.setObjectName("centralWidget")

        # Setup Grids
        self.gridLayoutWidget = self.setupGrid(self.centralWidget, "gridLayoutWidget", [0, 0, 721, 71])
        self.gridLayoutWidget_2 = self.setupGrid(self.centralWidget, "gridLayoutWidget_2", [720, 0, 81, 71])
        self.gridLayoutWidget_3 = self.setupGrid(self.centralWidget, "gridLayoutWidget_3", [-10, 70, 811, 501])

        self.TitleLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.TitleLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.TitleLayout.setContentsMargins(0, 0, 0, 0)
        self.TitleLayout.setVerticalSpacing(6)
        self.TitleLayout.setObjectName("TitleLayout")

        font = self.setupFont("PT Serif", 32, True, 75, QtGui.QFont.NoAntialias)

        self.title = QtWidgets.QLabel(self.gridLayoutWidget)
        self.title.setFont(font)
        self.title.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.title.setMouseTracking(False)
        self.title.setTabletTracking(False)
        self.title.setFocusPolicy(QtCore.Qt.NoFocus)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.TitleLayout.addWidget(self.title, 0, 0, 1, 1)

        self.SettingsGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.SettingsGrid.setContentsMargins(0, 0, 0, 0)
        self.SettingsGrid.setObjectName("SettingsGrid")

        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())

        self.pushButton.setEnabled(True)
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButton.setText("")

        app_icon_path = get_config(name='APP_ICON')
        settings_icon = QtGui.QIcon()
        settings_icon.addPixmap(QtGui.QPixmap(os.getcwd() + app_icon_path), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.pushButton.setIcon(settings_icon)
        self.pushButton.setIconSize(QtCore.QSize(64, 64))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.SettingsGrid.addWidget(self.pushButton, 0, 0, 1, 1)

        self.mainGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.mainGrid.setContentsMargins(0, 0, 0, 0)
        self.mainGrid.setObjectName("mainGrid")

        font = self.setupFont("PT Serif", 24, False, 50)

        self.finderButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.finderButton.setMaximumSize(QtCore.QSize(512, 16777215))
        self.finderButton.setFont(font)
        self.finderButton.setAutoDefault(False)
        self.finderButton.setDefault(False)
        self.finderButton.setFlat(False)
        self.finderButton.setObjectName("finderButton")
        self.mainGrid.addWidget(self.finderButton, 0, 0, 1, 1)
        Main.setCentralWidget(self.centralWidget)

        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Main.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Визуализатор"))
        self.title.setText(_translate("Main", "Визуализатор"))
        self.finderButton.setText(_translate("Main", "Выбрать аудио"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
